# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
    paths:
      - '**/*.ts'
      - package.json
      - package-lock.json
  merge_group:
  pull_request:
    branches: [ main ]
    paths:
      - '**/*.ts'
      - package.json
      - package-lock.json

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x, 22.x]

    steps:
    - name: Checkout to Repository
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install PNPM
      uses: pnpm/action-setup@v4

    - name: Install Dependencies
      run: pnpm install

    - name: Lint
      run: pnpm run lint

    - name: Build
      run: pnpm run build

    - name: Test
      run: pnpm run test
